# Generated by Django 4.1.4 on 2023-01-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_remove_task_operators_team_task_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="starting_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="phone_number",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=12, null=True
            ),
        ),
    ]
