# Generated by Django 4.1.4 on 2023-01-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_task_manger"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="manger",
            new_name="manager",
        ),
    ]
