# Generated by Django 4.1.4 on 2023-01-08 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_rename_manger_task_manager"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Loction",
            new_name="Location",
        ),
    ]
