# Generated by Django 4.1.4 on 2023-01-09 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0006_rename_loction_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="last_location",
            new_name="additional",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="main_location",
            new_name="area",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="more_location",
            new_name="location",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="loction",
            new_name="location",
        ),
        migrations.RemoveField(
            model_name="task",
            name="manager",
        ),
        migrations.AddField(
            model_name="location",
            name="code",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.CharField(blank=True, max_length=50, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "site_image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="location",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.site",
            ),
        ),
    ]
